"use strict";
exports.__esModule = true;
var MergeSort_1 = require("./MergeSort");
var quickSort_1 = require("./quickSort");
var search_1 = require("./search");
var test = require("./TestCases");
var sortedArray;
sortedArray = MergeSort_1["default"](test.case1);
console.log(search_1["default"](sortedArray, -2932));
sortedArray = quickSort_1["default"](test.case1);
console.log(search_1["default"](sortedArray, -2932));
sortedArray = MergeSort_1["default"](test.case2);
console.log(search_1["default"](sortedArray, 501));
sortedArray = quickSort_1["default"](test.case2);
console.log(search_1["default"](sortedArray, 501));
sortedArray = MergeSort_1["default"](test.case3);
console.log(search_1["default"](sortedArray, 2086));
sortedArray = quickSort_1["default"](test.case3);
console.log(search_1["default"](sortedArray, 2086));
sortedArray = MergeSort_1["default"](test.case4);
console.log(search_1["default"](sortedArray, 3879));
sortedArray = quickSort_1["default"](test.case4);
console.log(search_1["default"](sortedArray, 3879));
