"use strict";
exports.__esModule = true;
var Street_1 = require("./Street");
var vehicle_1 = require("./vehicle");
var WallStreet = new Street_1.Street('Wall street', 25, 3, false);
var tesla = [new vehicle_1.Car(true, 5, 'Electric', 20)];
var toyota = [new vehicle_1.Car(true, 5, 'Hybrid', 25), new vehicle_1.Car(true, 5, 'Gasoline', 22)];
var honda = [new vehicle_1.Motorcycle(true, 1, 'Gasoline', 23)];
WallStreet.increaseTraffic(tesla.length + toyota.length + honda.length);
WallStreet.printTraffic();
toyota[1].setSpeed(70);
toyota[1].drift();
